// <auto-generated />
using System;
using Acme_Courses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acme_Courses.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251204094026_New database")]
    partial class Newdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Finnish_Swedish_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acme_Courses.Elev", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KontaktUppgiftID")
                        .HasColumnType("int");

                    b.Property<int>("UtbildningsID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Elever");
                });

            modelBuilder.Entity("Acme_Courses.KontaktUppgift", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ElevID")
                        .HasColumnType("int");

                    b.Property<string>("KontaktInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktTyp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kontaktuppgifter");
                });

            modelBuilder.Entity("Acme_Courses.Kurs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Beskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SlutDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtbildningID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UtbildningID");

                    b.ToTable("Kurser");
                });

            modelBuilder.Entity("Acme_Courses.Utbildning", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Beskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Utbildningar");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Beskrivning = "Backend-Utvecklare",
                            Namn = "BUV25"
                        },
                        new
                        {
                            ID = 2,
                            Beskrivning = "Frontend-Utvecklare",
                            Namn = "FUV25"
                        },
                        new
                        {
                            ID = 3,
                            Beskrivning = "Fullstack-Utvecklare",
                            Namn = "FSUV25"
                        });
                });

            modelBuilder.Entity("ElevUtbildning", b =>
                {
                    b.Property<int>("EleverID")
                        .HasColumnType("int");

                    b.Property<int>("UtbildningarID")
                        .HasColumnType("int");

                    b.HasKey("EleverID", "UtbildningarID");

                    b.HasIndex("UtbildningarID");

                    b.ToTable("ElevUtbildning");
                });

            modelBuilder.Entity("Acme_Courses.Kurs", b =>
                {
                    b.HasOne("Acme_Courses.Utbildning", "Utbildning")
                        .WithMany("Kurser")
                        .HasForeignKey("UtbildningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utbildning");
                });

            modelBuilder.Entity("ElevUtbildning", b =>
                {
                    b.HasOne("Acme_Courses.Elev", null)
                        .WithMany()
                        .HasForeignKey("EleverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acme_Courses.Utbildning", null)
                        .WithMany()
                        .HasForeignKey("UtbildningarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Acme_Courses.Utbildning", b =>
                {
                    b.Navigation("Kurser");
                });
#pragma warning restore 612, 618
        }
    }
}
