// <auto-generated />
using System;
using Acme_Courses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acme_Courses.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251205150252_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Finnish_Swedish_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acme_Courses.Elev", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Elever");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Efternamn = "Andersson",
                            Förnamn = "Anna"
                        },
                        new
                        {
                            ID = 2,
                            Efternamn = "Berg",
                            Förnamn = "Björn"
                        },
                        new
                        {
                            ID = 3,
                            Efternamn = "Eriksson",
                            Förnamn = "Erik"
                        },
                        new
                        {
                            ID = 4,
                            Efternamn = "Svensson",
                            Förnamn = "Sara"
                        },
                        new
                        {
                            ID = 5,
                            Efternamn = "Lind",
                            Förnamn = "Lina"
                        },
                        new
                        {
                            ID = 6,
                            Efternamn = "Olsson",
                            Förnamn = "Oskar"
                        });
                });

            modelBuilder.Entity("Acme_Courses.KontaktUppgift", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ElevID")
                        .HasColumnType("int");

                    b.Property<string>("KontaktInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktTyp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ElevID");

                    b.ToTable("Kontaktuppgifter");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ElevID = 1,
                            KontaktInfo = "anna.andersson@example.com",
                            KontaktTyp = "E-post"
                        },
                        new
                        {
                            ID = 2,
                            ElevID = 1,
                            KontaktInfo = "070-1111111",
                            KontaktTyp = "Telefon"
                        },
                        new
                        {
                            ID = 3,
                            ElevID = 2,
                            KontaktInfo = "bjorn.berg@example.com",
                            KontaktTyp = "E-post"
                        },
                        new
                        {
                            ID = 4,
                            ElevID = 2,
                            KontaktInfo = "070-2222222",
                            KontaktTyp = "Telefon"
                        },
                        new
                        {
                            ID = 5,
                            ElevID = 3,
                            KontaktInfo = "erik.eriksson@example.com",
                            KontaktTyp = "E-post"
                        },
                        new
                        {
                            ID = 6,
                            ElevID = 3,
                            KontaktInfo = "070-3333333",
                            KontaktTyp = "Telefon"
                        },
                        new
                        {
                            ID = 7,
                            ElevID = 4,
                            KontaktInfo = "sara.svensson@example.com",
                            KontaktTyp = "E-post"
                        },
                        new
                        {
                            ID = 8,
                            ElevID = 4,
                            KontaktInfo = "070-4444444",
                            KontaktTyp = "Telefon"
                        },
                        new
                        {
                            ID = 9,
                            ElevID = 5,
                            KontaktInfo = "lina.lind@example.com",
                            KontaktTyp = "E-post"
                        },
                        new
                        {
                            ID = 10,
                            ElevID = 5,
                            KontaktInfo = "070-5555555",
                            KontaktTyp = "Telefon"
                        },
                        new
                        {
                            ID = 11,
                            ElevID = 6,
                            KontaktInfo = "oskar.olsson@example.com",
                            KontaktTyp = "E-post"
                        },
                        new
                        {
                            ID = 12,
                            ElevID = 6,
                            KontaktInfo = "070-6666666",
                            KontaktTyp = "Telefon"
                        });
                });

            modelBuilder.Entity("Acme_Courses.Kurs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Beskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SlutDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtbildningID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UtbildningID");

                    b.ToTable("Kurser");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Beskrivning = "Introduktion till C# och .NET",
                            Namn = "C# Grund",
                            SlutDatum = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDatum = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UtbildningID = 1
                        },
                        new
                        {
                            ID = 2,
                            Beskrivning = "SQL Server och EF Core",
                            Namn = "SQL Grund",
                            SlutDatum = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDatum = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UtbildningID = 1
                        },
                        new
                        {
                            ID = 3,
                            Beskrivning = "HTML, CSS och JavaScript",
                            Namn = "Frontend 1",
                            SlutDatum = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDatum = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UtbildningID = 2
                        },
                        new
                        {
                            ID = 4,
                            Beskrivning = "Komponenter och state",
                            Namn = "React Grund",
                            SlutDatum = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDatum = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UtbildningID = 2
                        },
                        new
                        {
                            ID = 5,
                            Beskrivning = "Bygg en komplett webbapplikation",
                            Namn = "Fullstack Projekt",
                            SlutDatum = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDatum = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UtbildningID = 3
                        },
                        new
                        {
                            ID = 6,
                            Beskrivning = "CI/CD och deployment",
                            Namn = "DevOps Introduktion",
                            SlutDatum = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDatum = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UtbildningID = 3
                        });
                });

            modelBuilder.Entity("Acme_Courses.Utbildning", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Beskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Utbildningar");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Beskrivning = "Backend-Utvecklare",
                            Namn = "BUV25"
                        },
                        new
                        {
                            ID = 2,
                            Beskrivning = "Frontend-Utvecklare",
                            Namn = "FUV25"
                        },
                        new
                        {
                            ID = 3,
                            Beskrivning = "Fullstack-Utvecklare",
                            Namn = "FSUV25"
                        });
                });

            modelBuilder.Entity("ElevUtbildning", b =>
                {
                    b.Property<int>("EleverID")
                        .HasColumnType("int");

                    b.Property<int>("UtbildningarID")
                        .HasColumnType("int");

                    b.HasKey("EleverID", "UtbildningarID");

                    b.HasIndex("UtbildningarID");

                    b.ToTable("ElevUtbildning");

                    b.HasData(
                        new
                        {
                            EleverID = 1,
                            UtbildningarID = 1
                        },
                        new
                        {
                            EleverID = 2,
                            UtbildningarID = 1
                        },
                        new
                        {
                            EleverID = 3,
                            UtbildningarID = 2
                        },
                        new
                        {
                            EleverID = 4,
                            UtbildningarID = 3
                        },
                        new
                        {
                            EleverID = 5,
                            UtbildningarID = 3
                        },
                        new
                        {
                            EleverID = 6,
                            UtbildningarID = 3
                        });
                });

            modelBuilder.Entity("Acme_Courses.KontaktUppgift", b =>
                {
                    b.HasOne("Acme_Courses.Elev", "Elev")
                        .WithMany("KontaktUppgifter")
                        .HasForeignKey("ElevID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elev");
                });

            modelBuilder.Entity("Acme_Courses.Kurs", b =>
                {
                    b.HasOne("Acme_Courses.Utbildning", "Utbildning")
                        .WithMany("Kurser")
                        .HasForeignKey("UtbildningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utbildning");
                });

            modelBuilder.Entity("ElevUtbildning", b =>
                {
                    b.HasOne("Acme_Courses.Elev", null)
                        .WithMany()
                        .HasForeignKey("EleverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acme_Courses.Utbildning", null)
                        .WithMany()
                        .HasForeignKey("UtbildningarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Acme_Courses.Elev", b =>
                {
                    b.Navigation("KontaktUppgifter");
                });

            modelBuilder.Entity("Acme_Courses.Utbildning", b =>
                {
                    b.Navigation("Kurser");
                });
#pragma warning restore 612, 618
        }
    }
}
